version: "3.8"
services:

  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./cert.key:/etc/nginx/cert.key

  api:
    build:
      context: .
      dockerfile: ApiDockerfile

  app:
    build:
      context: .
      dockerfile: AppDockerfile
    environment:
      VITE_EMAILS_JS_KEY: "${EMAILS_JS_KEY}"