<template>
  <div>
    <v-card v-if="generatedImage" max-width="1024px" class="mx-auto my-12" tile color="#FAFAFAFF">
      <v-card-text>
        <v-img :src="generatedImage"></v-img>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn
            color="success"
            :loading="generationBeingProcessed"
            @click="download"
            :x-large="!$vuetify.breakpoint.xs"
        >
          {{ $t('download') }}
        </v-btn>
        <v-spacer></v-spacer>
      </v-card-actions>
    </v-card>
    <canvas id="myCanvas" :width="canvasWidth" :height="canvasHeight" hidden>
      {{ $t('html5CanvasUnsupportedErrorMsg') }}
    </canvas>
  </div>
</template>
<script>
export default {
  props: {
    skills: {
      type: Array,
      default: () => []
    },
    brandImage: {
      type: String,
      default: () => null
    },
    logoSize: {
      type: Number,
      default: () => 40 * 4
    },
    backgroundColor: {
      type: String,
      default: () => "#FFFFEFFF"
    }
  },
  data: () => ({
    canvasWidth: 800 * 4,
    canvasHeight: 200 * 4,
    logoMargin: 4 * 4,
    logosAreaWidth: 800 * 4,
    generatedImage: null,
    generationBeingProcessed: false,
    maxBrandImageWidth: 100 * 4,
    maxBrandImageHeight: 100 * 4
  }),
  computed: {
    logoArea() {
      return this.logoSize + 2 * this.logoMargin;
    },
    nbLogoPerRow() {
      return Math.floor(this.logosAreaWidth / this.logoArea);
    }
  },
  methods: {
    computeCoordinate(index) {
      let x = (index % this.nbLogoPerRow) + 1;
      let y = Math.floor(index / this.nbLogoPerRow) + 1;
      return {
        x: this.canvasWidth - x * this.logoArea,
        y: this.canvasHeight - y * this.logoArea,
      };
    },
    generate() {
      this.$emit("in-progress", true);
      this.generationBeingProcessed = true;

      // Init canvas
      let canvas = document.createElement("canvas");
      canvas.width = this.canvasWidth;
      canvas.height = this.canvasHeight;

      // Color the canvas
      let ctx = canvas.getContext("2d");
      ctx.fillStyle = this.backgroundColor;
      ctx.fillRect(0, 0, this.canvasWidth, this.canvasHeight);

      // Append text
      let font = 30;
      ctx.font = font + "px small-caps bold Arial"
      ctx.fillStyle = '#616161FF';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'bottom';
      ctx.save();
      let text = "Generated by bannershake.com"
      let xText = font;
      let yText = ctx.measureText(text).width;
      ctx.translate(xText, yText);
      ctx.rotate(-Math.PI / 2);
      ctx.fillText(text, 0, font / 4);
      ctx.restore();

      // Append brand image
      if (this.brandImage) {
        let brand = new Image;
        let _this = this;
        brand.addEventListener("load", function () {
          let width = this.naturalWidth;
          let height = this.naturalHeight;
          if (this.naturalWidth > _this.maxBrandImageWidth) {
            width = _this.maxBrandImageWidth;
            height = width * (this.naturalHeight / this.naturalWidth);
            if (height > (_this.maxBrandImageHeight)) {
              height = _this.maxBrandImageHeight;
              width = height * (this.naturalWidth / this.naturalHeight);
            }
          } else if (this.naturalHeight > _this.maxBrandImageHeight) {
            height = _this.maxBrandImageHeight;
            width = height * (this.naturalWidth / this.naturalHeight);
            if (width > _this.maxBrandImageWidth) {
              width = _this.maxBrandImageWidth;
              height = width * (this.naturalHeight / this.naturalWidth);
            }
          }
          let x = _this.logoSize;
          let y = (_this.canvasHeight / 2) - (height / 2);
          ctx.drawImage(brand, x, y, width, height);

          let xLine = (2 * x) + width;
          let yLine = _this.canvasHeight / 8;
          ctx.beginPath();
          ctx.moveTo(xLine, yLine);
          ctx.lineTo(xLine, 7 * yLine);
          ctx.lineWidth = 4;
          ctx.strokeStyle = '#616161FF';
          ctx.stroke();

          _this.logosAreaWidth = _this.canvasWidth - xLine;

          _this.generateLogos(canvas);
        });
        brand.src = this.brandImage;
      } else {
        this.generateLogos(canvas);
      }
    },
    generateLogos(canvas) {
      // Append selected logos
      let _this = this;
      let drawnLogos = 0;
      let ctx = canvas.getContext("2d");
      this.skills.forEach((element, index) => {
        let image = new Image();
        image.addEventListener("load", function () {
          let height = _this.logoSize;
          let width = _this.logoSize * (this.naturalWidth / this.naturalHeight);
          if (width > _this.logoSize) {
            width = _this.logoSize;
            height = _this.logoSize * (this.naturalHeight / this.naturalWidth);
          }
          let coordinate = _this.computeCoordinate(index);
          let yShift = 0;
          if (height < _this.logoSize) {
            yShift = (_this.logoSize - height) / 2;
          }
          ctx.drawImage(
              image,
              coordinate.x,
              coordinate.y + yShift,
              width,
              height
          );
          drawnLogos++;
          if (drawnLogos === _this.skills.length) {
            _this.generatedImage = canvas.toDataURL("image/png;base64");
            _this.generationBeingProcessed = false;
            _this.$emit("in-progress", false);
          }
        });
        image.src = require("../static/" + element);
      });
    },
    download() {
      let lnk = document.createElement("a"),
          e;

      /// the key here is to set the download attribute of the a tag
      lnk.download = "skills-banner.png";

      /// convert canvas content to data-uri for link. When download
      /// attribute is set the content pointed to by link will be
      /// pushed as "download" in HTML5 capable browsers
      lnk.href = this.generatedImage;

      /// create a "fake" click-event to trigger the download
      if (document.createEvent) {
        e = document.createEvent("MouseEvents");
        e.initMouseEvent(
            "click",
            true,
            true,
            window,
            0,
            0,
            0,
            0,
            0,
            false,
            false,
            false,
            false,
            0,
            null
        );

        lnk.dispatchEvent(e);
      } else if (lnk.fireEvent) {
        lnk.fireEvent("onclick");
      }
    }
  }
}
</script>
