name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push Docker image for API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ApiDockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ghcr.io/boukadam/bannershake-api:main
          labels: |
            org.opencontainers.image.title=bannershake-api
            org.opencontainers.image.authors=Mohammed BOUKADA
            org.opencontainers.image.documentation=https://bannershake.com
            org.opencontainers.image.version=main
            org.opencontainers.image.created=${{ github.event.repository.updated_at}}
            org.opencontainers.image.revision=${{ github.sha }}
      - name: Build and push Docker image for APP
        uses: docker/build-push-action@v5
        with:
          context: .
          file: AppDockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ghcr.io/boukadam/bannershake-app:main
          labels: |
            org.opencontainers.image.title=bannershake-app
            org.opencontainers.image.authors=Mohammed BOUKADA
            org.opencontainers.image.documentation=https://bannershake.com
            org.opencontainers.image.version=main
            org.opencontainers.image.created=${{ github.event.repository.updated_at}}
            org.opencontainers.image.revision=${{ github.sha }}